eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
spring:
  datasource:
    username: root
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: root
  h2:
    console:
      enabled: 'true'
  data:
    rest:
      base-path: /api/v1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: 'true'
